server:
  port: 9003

spring:
  application:
    name: BMS-MONGODB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/bms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&autoReconnect=true&zeroDateTimeBehavior=convertToNull
  data:
    mongodb:
      uri: mongodb://bmsuser:110514zy..@106.54.31.196:27017/bms
      #username: bms
      #password: QWEasd@123